### ISSUE TITLE
HAL vs LL 

### ISSUE THREAD

**Issue by MuratovAS** [canokeys/canokey-stm32#5]
Good day.
What is the point of creating a project on HAL, and then use the call from LL. Isn't it better to use one? Why produce libraries in the project .......

Добрый день.
Какой смысл в создание проекта на HAL, а затем использовать вызов из LL. Разве не лучше использовать что-то одно? Зачем плодить библиотеки в проекте .......

**Comment by z4yx** [comment]
The initial source code was generated by CubeMX, which uses the HAL library to initialize peripherals. Using struct and macro makes the initialization procedure easy to understand.

For timing-critical or simple operations, I prefer to use LL calls to reduce the overhead of function calls.
